In [8]:
import numpy as np

# using list to create numpy arrays
list_arr = [1,2,3,4]
arr = np.array(list_arr)
arr

# using tuples to create numpy array
# TASK: CREATE A NUMPY ARRAY USING A TUPLE
tuple_arr = (1,2,3,4)
arr = np.array(tuple_arr)
arr




array([1, 2, 3, 4])

In [18]:
# DIMENSIONS IN NUMPY

#  0-D ARRAY
zero_d = np.array(53)
zero_d.ndim

# 1-D ARRAY
one_d = np.array([1,2,3,4])
one_d.ndim

# 2-D ARRAY
two_d = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
two_d.ndim

# TASK: CREATE A 3-D ARRAY
three_d = np.array([[[1,2,3,4], [5,6,7,8]]])
three_d.ndim

3

In [62]:
# CREATING MUMPY ARRAYS WITH THE FOLLOWING NUMPY METHODS
# 1. linspace
# 2. arange
# 3. random
# 4. zeroes
# 5. ones
# 6. identities

# ONES ARRAY
from numpy import identity


arr_ones = np.ones((4,5))
arr_ones

# ZEROES ARRAY
zeroes_arr = np.zeros((3,4))
zeroes_arr

# ARANGE ARRAYS
arange_arr = np.arange(1,5)
arange_arr

# LINSPACES ARRAYS
linspace_arr = np.linspace(1,5,10)
linspace_arr

# RANDOM ARRAYS
# SAMPLE 1
random_arr = np.random.randint(2,10,10)

# SAMPLE 2
random_arr = np.random.randint(2, size=10)

# SAMPLE 3
random_arr = np.random.randint(2, size=(2,4))
random_arr

# IDENTITIES ARRAY
identity_arr = np.identity(4)
identity_arr


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [77]:
# NUMPY ATTRIBUTES
# 1. ndim
# 2. shape
# 3. size
# 4. dtype

# NDIM ATTRIBUTES
# new_arr = np.array([
#     [1,2,3,4], 
#     [5,6,7,8]
# ])
new_arr = np.array([1, 2, 4 ,2,3,4])
new_arr.ndim
new_arr.shape

# SHAPE ATTRIBUTES
# row, col = new_arr.shape
# print(f'this has {row} rows and {col} columns')

# SIZE ATTRIBUTES
# new_arr.size

# DTYPE
new_arr.dtype

# DTYPE SAMPLE 2
dtype_arr = np.array([1,2,3], dtype=np.float64)
dtype_arr

array([1., 2., 3.])

In [11]:
# DAY 1 CHALLENGES

# TASK 1
# given the following number between 1 and 6
# create a two dimensional array, with the numbers

# TASK 2
# create a four dimensional array 

# TASK 3
# Create a 2-D array containing two arrays with the values 1,2,3 and 4,5,6:


2

In [9]:
# OPERATIONS IN NUMPY
import numpy as np

arr1 = np.array([10, 10])
arr2 = np.array([10, 10])
arr3 = np.array([[10, 20], [10, 20]])

# ADDITION
print('Addition', np.add(arr1, arr2))

# SUBTRACTION
print('Subtraction', np.subtract(arr1, arr2))

# MULTIPLICATION
print('Multiply', np.multiply(arr1, arr2))

# DIVISION
print('Division', np.divide(arr1, arr2))

# POWER - METHOD 1
print('Power Method 1', np.power(arr1, 2))

# POWER - METHOD 2
print('Power Method 2', np.power(arr1, arr2))

# MOD => MODULUS
print('Mod', np.mod(arr1, arr2))

# NUMPY OPERATION WITH MORE THAN ONE DIMENSIONS
print('Addition with more dimensions', np.add(arr2, arr3))



Addition [20 20]
Subtraction [0 0]
Multiply [100 100]
Division [1. 1.]
Power Method 1 [100 100]
Power Method 2 [1410065408 1410065408]
Mod [0 0]
Addition with more dimensions [[20 30]
 [20 30]]


In [32]:
from scipy import stats
# AGGREGATE FUNCTIONS AND STATISTICS

# 1. Sum
# 2. prod
# 3. mean
# 4. std
# 5. var
# 6. min
# 7. max
# 8. argmin
# 9. argmax
# 10. median

# SUM
arr = np.array([1,2,3,4,5, 5,5])
print('Sum: ', np.sum(arr))

# PROD
print('Prod: ', np.prod(arr))

# MEAN
print('Mean: ', np.mean(arr))

# STD => STANDARD DEVIATION
print('Std: ', np.std(arr))

# VAR => VARIANCE
print('Var: ', np.var(arr))

# MIN => MINIMUM
print('Min: ', np.min(arr))

# MAX => MAXIMUM
print('Max: ', np.max(arr))

# ARGMIN => RETURNS THE MINIMUM INDEX
print('Argmin: ', np.argmin(arr))

# ARGMAX => RETURNS THE MAXIMUM INDEX
print('Argmax: ', np.argmax(arr))

# MEDIAN
print('Median: ', np.median(arr))

# MODE
print('Mode', stats.mode(arr))


Sum:  25
Prod:  3000
Mean:  3.5714285714285716
Std:  1.498298354528788
Var:  2.2448979591836737
Min:  1
Max:  5
Argmin:  0
Argmax:  4
Median:  4.0
Mode ModeResult(mode=array([5]), count=array([3]))


In [37]:
# ARRAY AXIS
arr = np.array([
    [1,2],
    [3,4],
    [5,6]
])

# arr.sum()
arr.sum(axis=0)
arr.sum(axis=1)

array([ 3,  7, 11])

In [54]:
# ARRAY INDEXING AND SLICING
arr = np.array([1,2,3,4,5])
# print(arr[-2])

arr2 = np.array([
    [1,2,3,4,5], 
    [6,7,8,9,10]
])

# Access 6
print(arr2[1,0])

# Access 9
print(arr2[1,3])

# Access 9
print(arr2[-1, -2])

6
9
9


In [68]:
# SLICING
arr = np.array([1,2,3,4,5,6,7])
arr2 = np.array([[1,2,3,4,5], [6,7,8,9,10]])

# Slice elements from index 1 to index 5
# print(arr[1:6])

# slice elements from index 4 to the end of the array
# print(arr[4:])

# slice elements from the beginning to index 4 (not included)
# print('Jessica', arr[:4])
# print('Brighten', arr[:4])

# slice from the index 3 from the end to index 1 from the end
print(arr[-3:-1])

arr2 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
# from the second element, slice elements from index 1 to index 4
print(arr2[1, 1:5])

[5 6]
[ 7  8  9 10]


In [70]:
# FANCY INDEXING
arr = np.arange(1,10)
index = np.array([2,3,4])
print(arr[index])

[3 4 5]


In [77]:
# BOOLEAN ARRAYS AND MASKING
# BOOLEAN INDEXING

# There are two methods of carrying out boolean masking
# Method one: Return the result array
# Method Two: Returns a boolean array

# Method One:
arr = np.arange(15)
# print('array', arr)

# using boolean masking
# print(arr[arr >= 8])
# print(arr[arr == 12])

# Method Two
arr = np.array([
    [0, 9, 0],
    [0, 7, 8],
    [6, 0, 1],
])
print('array', arr)
# create a mask array
mask = arr > 5
# print the mask array => return boolean
print('mask', mask)

# print out the filtered array using both methods
print('the mask', arr[mask])
print('the mask, another method', arr[arr > 5])

array [[0 9 0]
 [0 7 8]
 [6 0 1]]
the mask [9 7 8 6]
the mask, another method [9 7 8 6]


In [3]:
# CHALLENGE
# 1. Create a two dimension array with two values as items ranging from 1-4, and another array with 1 dimension, perform an addition, subtraction, multiplication, division and power operation with both arrays, hence also get the remainder of your division.

# 2. Given the array [[1,2,3,5,8], [6,7,8,9,10]], find the median, sum, and max of the second item in the array, if the max is equal to 10, hence return the index of the index of the max, else return the index of the index of the min value

# 3. Given the array 
# arr = np.array([
#     [1,2],
#     [3,4],
#     [5,6]
# ])
# calculate the sum of the array by column and rows

# 4. given the array [1,2,4,5,6,7,8]
# use fancy indexing to get from index 2 to 

# 5. given the array below, get the last value of the first element and the second element, add and subtract both values, use the result of both values to create a 2-dimension array with random values with a total length of values each in both elements
# arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

# 6. given the array below, find the odd numbers in the array and return the result array and the boolean array
# arr = np.array([
#     [2, 9, 5],
#     [4, 7, 8],
#     [6, 3, 1],
# ])

15

In [6]:
# BROADCASTING
import numpy as np

arr1 = np.array([[1,2], [3,4], [5,6]])
arr2 = np.array([[1,2], [1,2], [1,2]])

np.add(arr1, arr2)

array([[2, 4],
       [4, 6],
       [6, 8]])

In [8]:
# UNIVERSAL FUNCTIONS

def add(x, y):
    return x + y

# sum = add(1,2)

sum = np.frompyfunc(add, 2, 1)
print(sum(
    [1,2,3], 
    [4,5,6])
)


[5 7 9]


In [21]:
# RESHAPING

# Reshaping means changing the shape of an array.
# The shape of an array is the number of elements in each dimension
# by reshaping we could add or remove dimensions or change the numbers of elements
# in each dimension.

# EXAMPLE 1
# Convert the following array 1-d array with 12 elements into a 2-d array
# arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
# newarr = arr.reshape(4,3)
# newarr

# EXAMPLE 2
# Convert the followoing 1-D array with 12 elements to 3-D ARRAY
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(2, 3, 2)

newarr

# EXMAPLE 3
# FLATTENING
# CONVERTING A MULTIDIMENSIONAL ARRAY TO A 1 DIMENSIONAL ARRAY
arr = np.array([[1, 2, 3], [4,5,6]])

print(arr)
newarr = arr.reshape(-1)
print(newarr)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


2

In [26]:
# SPLITING AND STACKING ARRAYS

# SPLITTING
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr, 3)
# print(newarr)

first, second, third = newarr
# print(first)
# print(second)
# print(third)

# STACKING
# Stack is used for joining multiple arrays. it joins along a new axis. it returns a numpy array
# to join two array, they must have the same shape and dimension
# stacking create a new array
a = np.array([1,2,3])
b = np.array([4,5,6])

# stacking the arrays a and b
# axis 1 = col
# axis 0 = row
c = np.stack((a,b), axis=1)
d = np.stack((a,b), axis=0)

print(c)
print('')
print(d)

[[1 4]
 [2 5]
 [3 6]]

[[1 2 3]
 [4 5 6]]


In [41]:
# INSERTING AND REMOVING ELEMENTS FROM A NUMPY ARRAY
a = np.array([1,2,3,4,5,6])
# print(a)

# delete/remove the first element
# print('removing the first element', np.delete(a, 0))

# delete the first and fifth element
# print('removing the 1st and 5th element', np.delete(a, [0,4]))

# using conditions
# print('removing 6 using conditions: ', np.delete(a, np.where(a == 6)))

# performing a delete by rows and cols
# GOAL: DELETE THE FIRST COLUMN
arr = [
    [1,2,3,4], 
    [5,6,7,8]
]
# columns
# print('deleting by column', np.delete(arr, 0, axis=1))

# GOAL: DELETE THE SECOND ROW
# print('Deleting the second row: ', np.delete(arr, 1, axis=0 ))

# DELETE USING FANCY INDEXING
arr2 = np.array([1,2,3,4,5,6,7,8,9,10])
indexList = [0,3,6]
arr = arr2[indexList]
print(arr)
print(arr2)

[1 4 7]
[ 1  2  3  4  5  6  7  8  9 10]


In [43]:
# SORTING

# sorting numbers
arr = np.array([3,2,0,1])
print(np.sort(arr))


# sorting strings
arr2 = np.array(['banana', 'cherry', 'apple'])
print(np.sort(arr2))


[0 1 2 3]
['apple' 'banana' 'cherry']
